# Author: Adib Keikhosravi, Ph.D.
# Staff Scientist, Laboratory of Receptor Biology and Gene Expression, CCR, NCI
# National Institutes of Health
# Email: adib.keikhosravi@nih.gov
# License: MIT License

"""Detailed parameter-help text for the P/Q Arm Analyzer GUI.

Each entry is used both as a hover tooltip and as the fixed help text opened by
clicking the round information button next to a parameter. The text is written
for interactive parameter tuning and avoids dataset-specific image dimensions.
"""

PARAMETER_INFO: dict[str, str] = {'image_path': 'Load image\n'
               '\n'
               'What it is: Opens a file browser so you can choose the microscopy image file to '
               'analyze. The plugin is intended for multi-channel 3D microscopy images and '
               'supports common formats such as LIF, CZI, ND2, IMS, OME-TIFF, TIFF, LSM, and Zarr '
               'when the corresponding reader packages are available.\n'
               '\n'
               'How it affects the result: The loaded file determines the raw intensity values, '
               'available scenes, available channels, z-stack size, and physical voxel spacing. '
               'All physical measurements in micrometers or cubic micrometers depend on the voxel '
               'spacing reported by the reader.\n'
               '\n'
               'How to check it: After loading, read the status box. Confirm that the CZYX shape, '
               'number of channels, number of z-slices, and Z/Y/X spacing look reasonable. If the '
               'displayed shape is unexpected, try another scene or check the reader '
               'dependencies.\n'
               '\n'
               'Tuning advice: This is not a segmentation parameter, but it is the first place to '
               'check when all later results look wrong. Wrong scene, wrong channel order, or '
               'wrong pixel size can make every measurement unreliable.',
 'preview_scene': 'Preview scene\n'
                  '\n'
                  'What it is: Selects one scene, series, field of view, position, or tile from '
                  'the image file for interactive preview.\n'
                  '\n'
                  'How it affects the result: The selected preview scene is the one displayed in '
                  'napari while you tune parameters. If no scenes are checked in the scene list, '
                  'the Analyze button uses this loaded preview scene.\n'
                  '\n'
                  'How to use it: Choose a representative scene, click Load selected scene for '
                  'preview, set the channel numbers, preview nuclei, and then preview P/Q arms. '
                  'Use this single scene for tuning before running a batch.\n'
                  '\n'
                  'Tuning advice: If your file contains multiple fields, tune on a field with '
                  'typical signal quality. After the settings work on that field, check the scenes '
                  'you want to analyze in batch.',
 'scene_checklist': 'Scenes to analyze\n'
                    '\n'
                    'What it is: A checkbox list of scenes detected in the image file.\n'
                    '\n'
                    'How it affects the result: If no scenes are checked, the plugin analyzes only '
                    'the currently loaded preview scene. If one or more scenes are checked, the '
                    'plugin analyzes all checked scenes with the current parameter set and creates '
                    'one result subfolder per scene.\n'
                    '\n'
                    'How to use it: First tune parameters on one preview scene. Then check the '
                    'scenes that should be processed with the same settings. This is useful when '
                    'one microscopy file contains many fields or positions.\n'
                    '\n'
                    'Tuning advice: Batch analysis assumes that the same channel assignments and '
                    'segmentation parameters are appropriate for all checked scenes. If different '
                    'scenes have very different brightness or focus quality, analyze them in '
                    'separate groups with separate configuration files.',
 'output_folder': 'Output folder\n'
                  '\n'
                  'What it is: The base folder where result files will be saved.\n'
                  '\n'
                  'How it affects the result: Single-scene analysis writes masks, CSV files, '
                  'plots, QC images, and configuration files directly into the selected folder. '
                  'Batch analysis writes one subfolder per checked scene.\n'
                  '\n'
                  'Saved reproducibility files: Every run saves pq_arm_analyzer_configuration.json '
                  'and analysis_parameters.json. These files record the parameter values and can '
                  'be used to reproduce or audit the run.\n'
                  '\n'
                  'Tuning advice: Use a new empty output folder for final runs. During testing, '
                  'use a separate temporary output folder so preview/test results do not mix with '
                  'final results.',
 'nuc_channel': 'Nucleus channel\n'
                '\n'
                'What it is: The 1-based channel number used for nuclei segmentation.\n'
                '\n'
                'How it affects the result: Cellpose uses this channel to create the nuclear label '
                'image. P/Q arm segmentation is performed inside each nucleus, so the nucleus '
                'channel controls the boundaries used for all later arm measurements.\n'
                '\n'
                'If the value is too low or too high: A wrong channel can make Cellpose segment '
                'background, P/Q signal, or another stain instead of nuclei. This causes wrong arm '
                'masks, volumes, overlaps, and radial positions.\n'
                '\n'
                'How to tune: First confirm the raw channel layer visually. If nuclei are missing, '
                'over-split, merged, or shifted, verify this channel before changing Cellpose '
                'diameter or downsampling.',
 'p_channel': 'P-arm channel\n'
              '\n'
              'What it is: The 1-based channel number used to detect the P arm signal.\n'
              '\n'
              'How it affects the result: The plugin extracts this channel inside each segmented '
              'nucleus, fits the selected arm-detection model, and produces P-arm masks, P '
              'volumes, P centroids, P radial positions, P shape metrics, and P/Q overlap '
              'metrics.\n'
              '\n'
              'If the value is wrong: The P mask may appear empty, may follow the Q signal, or may '
              'segment an unrelated raw channel.\n'
              '\n'
              'How to tune: Confirm the P arm channel layer in napari before changing GMM '
              'thresholds. If P and Q appear swapped, correct this value and the Q-arm channel '
              'value first.',
 'q_channel': 'Q-arm channel\n'
              '\n'
              'What it is: The 1-based channel number used to detect the Q arm signal.\n'
              '\n'
              'How it affects the result: The plugin uses this channel to calculate Q-arm masks, Q '
              'volumes, Q centroids, Q radial positions, Q shape metrics, and P/Q overlap '
              'metrics.\n'
              '\n'
              'If the value is wrong: Q-arm segmentation may be empty, follow P-arm signal, or '
              'detect another channel.\n'
              '\n'
              'How to tune: Tune P and Q channel assignments separately. The two channels may have '
              'different brightness, noise, background, or bleaching behavior, so their downstream '
              'GMM class settings can also differ.',
 'cellpose_model': 'Cellpose model\n'
                   '\n'
                   'What it is: The pretrained Cellpose model used to segment nuclei.\n'
                   '\n'
                   'Available choices: The nuclei model is the recommended starting point for '
                   'nuclear stains. Cytoplasm-style models can be tested only when the nucleus '
                   'channel does not resemble a standard nuclear stain.\n'
                   '\n'
                   'How it affects the result: The model changes the object appearance that '
                   'Cellpose expects. A model that does not match the image can under-segment, '
                   'over-segment, or merge objects.\n'
                   '\n'
                   'How to tune: Start with nuclei. Change the model only if nuclei are '
                   'consistently poor after reasonable diameter and downsample adjustments.',
 'cellpose_mode': 'Nuclei segmentation mode\n'
                  '\n'
                  'What it is: Controls how Cellpose is applied to the z-stack.\n'
                  '\n'
                  'Cellpose 3D whole volume: Runs Cellpose as a 3D segmentation. This can use '
                  'z-continuity and may better preserve 3D nuclear shapes, but it can be slower '
                  'and can use more memory.\n'
                  '\n'
                  'Cellpose 2D stack batch + overlap stitch: Runs 2D Cellpose on z-slices and then '
                  'stitches labels across adjacent z-slices using overlap. This is often the '
                  'practical starting mode for large multi-slice stacks.\n'
                  '\n'
                  'Cellpose 2D parallel slices + overlap stitch: Runs the 2D slice path with CPU '
                  'parallelization. It can help on CPU-only systems, but if GPU is enabled, '
                  'multiple GPU workers are avoided to prevent conflicts.\n'
                  '\n'
                  'How it affects the result: 3D mode may better preserve 3D continuity. 2D '
                  'stitching modes are often faster and may be easier to run on large fields, but '
                  'the z-stitch overlap parameter becomes important.\n'
                  '\n'
                  'How to tune: If nuclei are broken into z-fragments, lower the z-stitch overlap '
                  'or try 3D mode. If nearby nuclei are incorrectly joined across slices, raise '
                  'the z-stitch overlap or decrease Cellpose diameter.',
 'gpu': 'Use GPU\n'
        '\n'
        'What it is: Allows Cellpose to run on a GPU if your Cellpose/PyTorch installation '
        'supports it.\n'
        '\n'
        'How it affects the result: GPU should mainly affect speed, not the intended segmentation. '
        'However, GPU memory limits can force you to change batch size or downsample.\n'
        '\n'
        'How to tune: Enable GPU when available. If Cellpose fails with memory errors, disable '
        'GPU, increase XY downsample, or reduce 2D batch size.',
 'diameter': 'Cell / nucleus diameter\n'
             '\n'
             'What it is: Approximate nucleus diameter in pixels after XY downsampling.\n'
             '\n'
             'How it affects the result: This is a size prior for Cellpose. If the diameter is too '
             'small, one real nucleus may be split into multiple labels. If it is too large, '
             'neighboring nuclei may merge.\n'
             '\n'
             'Increase when: Nuclei are split into too many small pieces.\n'
             '\n'
             'Decrease when: Neighboring nuclei are merged into one object.\n'
             '\n'
             'Practical tuning: Change in small steps and rerun Preview nuclei masks. Tune this '
             'before judging P/Q arm segmentation because arm detection depends on the nucleus '
             'mask.',
 'xy_downsample': 'XY downsample factor\n'
                  '\n'
                  'What it is: Reduces the image size in X and Y before Cellpose. A value of 1 '
                  'means no downsampling. A value of 2 halves width and height and reduces the XY '
                  'pixel count by about four-fold.\n'
                  '\n'
                  'How it affects the result: Increasing this value speeds Cellpose and reduces '
                  'memory usage. However, it makes boundaries less precise and can make small '
                  'nuclei harder to segment.\n'
                  '\n'
                  'Increase when: Cellpose is too slow or runs out of memory during preview.\n'
                  '\n'
                  'Decrease when: Nuclear boundaries look blocky, small nuclei are lost, or '
                  'adjacent nuclei are incorrectly merged because detail was removed.\n'
                  '\n'
                  'Practical tuning: Use a higher value for quick preview and a lower value for '
                  'final analysis if boundary accuracy matters.',
 'min_nucleus_volume': 'Minimum nucleus volume\n'
                       '\n'
                       'What it is: The smallest physical volume, in cubic micrometers, that a '
                       'Cellpose object must have to remain in the nuclei label image. The default '
                       'is 5 um^3.\n'
                       '\n'
                       'How it affects the result: Objects smaller than this volume are removed '
                       'after Cellpose. This helps remove debris, tiny fragments, or false nuclear '
                       'labels.\n'
                       '\n'
                       'Increase when: Many tiny false nuclei are present.\n'
                       '\n'
                       'Decrease when: Small real nuclei are being removed.\n'
                       '\n'
                       'Mathematical meaning: Volume is voxel count multiplied by voxel size in z, '
                       'y, and x. Because it uses physical units, the same value can be used '
                       'across images with different pixel sizes if metadata are correct.',
 'cellpose_batch': '2D batch size\n'
                   '\n'
                   'What it is: Number of z-slices passed to Cellpose together when using 2D '
                   'stack-batch mode.\n'
                   '\n'
                   'How it affects the result: This mainly affects speed and memory rather than '
                   'segmentation logic. Larger batches can improve GPU or CPU throughput but '
                   'require more memory.\n'
                   '\n'
                   'Increase when: The system has enough memory and Cellpose overhead is slowing '
                   'processing.\n'
                   '\n'
                   'Decrease when: You get memory errors or instability during nuclei preview.',
 'cellpose_overlap': '2D z-stitch overlap fraction\n'
                     '\n'
                     'What it is: The minimum overlap required to link 2D Cellpose labels in '
                     'neighboring z-slices into the same 3D nucleus.\n'
                     '\n'
                     'How it affects the result: Higher values require stronger slice-to-slice '
                     'overlap before labels are joined. Lower values join more labels across z.\n'
                     '\n'
                     'Increase when: Adjacent nuclei are incorrectly merged across z.\n'
                     '\n'
                     'Decrease when: The same nucleus is broken into multiple z-fragments.\n'
                     '\n'
                     'Practical range: Small positive values often work well. Always check nuclei '
                     'in 3D or across z after changing this parameter.',
 'auto_cellpose': 'Auto-run nuclei preview when Cellpose parameters change\n'
                  '\n'
                  'What it is: Automatically reruns nuclei segmentation after a Cellpose-related '
                  'parameter changes.\n'
                  '\n'
                  'How it affects the result: It does not change the algorithm; it only controls '
                  'whether preview runs automatically.\n'
                  '\n'
                  'When to enable: Useful for small images or quick tests.\n'
                  '\n'
                  'When to disable: Recommended for large 3D images or slow Cellpose settings. '
                  'Disable it and click Preview nuclei masks manually when ready.',
 'parallel_jobs': 'Worker count\n'
                  '\n'
                  'What it is: Number of CPU workers used for per-nucleus P/Q arm detection and '
                  'measurement. A value of 0 lets the plugin choose automatically.\n'
                  '\n'
                  'How it affects the result: It changes speed, not the mathematical result. More '
                  'workers can speed analysis when many nuclei are present, but too many workers '
                  'can increase memory pressure or slow the workstation.\n'
                  '\n'
                  'How to tune: Start with 0 or a moderate number. If the computer becomes '
                  'unresponsive or memory use is high, reduce the worker count. Use sequential '
                  'mode only for debugging.',
 'parallel_backend': 'Backend for per-nucleus work\n'
                     '\n'
                     'What it is: Controls how the plugin parallelizes per-nucleus P/Q arm '
                     'detection.\n'
                     '\n'
                     'threading: Usually the best starting backend because worker threads can '
                     'share large image arrays in memory.\n'
                     '\n'
                     'loky: Uses separate processes. This can help some CPU-heavy tasks but can '
                     'duplicate memory and may be slower for large 3D arrays.\n'
                     '\n'
                     'sequential: Uses one worker. It is slow but easiest for debugging.\n'
                     '\n'
                     'How to tune: Start with threading. Use loky only if threading is not using '
                     'CPU effectively and memory is sufficient.',
 'method': 'Detection method\n'
           '\n'
           'What it is: Selects the P/Q arm detection algorithm.\n'
           '\n'
           'Legacy 1D GMM: Fits intensity classes inside each nucleus and keeps selected bright '
           'classes. It is simple and useful as a baseline, but it can segment noise because it '
           'always tries to split intensities.\n'
           '\n'
           'Upgraded 1D GMM + gate + scoring: Recommended default. It adds field-level '
           'normalization, a presence/absence gate, probability thresholding, and '
           'connected-component scoring.\n'
           '\n'
           'MRF/CRF refinement: Starts from the upgraded method and adds spatial boundary '
           'refinement. It encourages neighboring voxels to agree while respecting intensity '
           'edges.\n'
           '\n'
           'How to tune: Start with Upgraded 1D GMM + gate + scoring. Switch to MRF/CRF when the '
           'correct general region is found but boundaries are noisy, jagged, or contain small '
           'holes. Use Legacy only as a comparison or for very clean images.',
 'gmm_components': 'Max GMM components\n'
                   '\n'
                   'What it is: Maximum number of Gaussian intensity classes fit inside each '
                   'nucleus. The default is 4.\n'
                   '\n'
                   'How it affects the result: With more components, the model can represent '
                   'multiple intensity groups, such as background-like, dim, medium, and bright '
                   'voxels.\n'
                   '\n'
                   'Increase when: Real P/Q signal has multiple brightness levels and lower '
                   'component counts miss true signal.\n'
                   '\n'
                   'Decrease when: The model splits noise into artificial signal classes, results '
                   'become unstable, or preview speed is too slow.\n'
                   '\n'
                   'Practical advice: The default value of 4 is paired with the default sorted '
                   'class index of 3, which keeps only the brightest component. If true signal is '
                   'missed, try lowering the P or Q sorted class index before making other '
                   'thresholds more permissive.',
 'auto_bic': 'Auto-choose 1D GMM components by BIC\n'
             '\n'
             'What it is: Lets the plugin compare GMMs with different component counts and choose '
             'a model using Bayesian information criterion.\n'
             '\n'
             'How it affects the result: It can adapt to nuclei with different intensity '
             'distributions, but it is slower and can make tuning less predictable because '
             'different nuclei may use different component counts.\n'
             '\n'
             'Enable when: Some nuclei need two classes while others need three or more classes.\n'
             '\n'
             'Disable when: You want maximum speed, maximum reproducibility, and a simpler '
             'interpretation of the sorted class index.',
 'p_min_class': 'P: keep sorted class index >=\n'
                '\n'
                'What it is: GMM components are sorted by mean intensity from dimmest to '
                'brightest. This parameter keeps P-channel components whose sorted class index is '
                'greater than or equal to the selected value. The default is 3.\n'
                '\n'
                'How it affects the result: A higher value keeps only the brightest P voxels and '
                'makes the P mask more conservative. A lower value includes dimmer P voxels and '
                'makes the mask more inclusive.\n'
                '\n'
                'For four components: 0 keeps all classes, 1 keeps the upper three classes, 2 '
                'keeps the upper two classes, and 3 keeps only the brightest class.\n'
                '\n'
                'Increase when: P masks include too much background or dim noise.\n'
                '\n'
                'Decrease when: P masks miss dim but real P signal.',
 'q_min_class': 'Q: keep sorted class index >=\n'
                '\n'
                'What it is: Same as the P sorted class threshold, but applied to the Q channel. '
                'The default is 3.\n'
                '\n'
                'How it affects the result: A higher value keeps only the brightest Q voxels and '
                'makes the Q mask more conservative. A lower value includes dimmer Q voxels and '
                'makes the mask more inclusive.\n'
                '\n'
                'For four components: 0 keeps all classes, 1 keeps the upper three classes, 2 '
                'keeps the upper two classes, and 3 keeps only the brightest class.\n'
                '\n'
                'How to tune: Tune Q independently from P. It is common for P and Q channels to '
                'have different brightness, noise, or background, so the best sorted class index '
                'may differ between channels.',
 'norm_mode': 'Normalization mode\n'
              '\n'
              'What it is: Defines how the plugin estimates field-level background intensity '
              'before upgraded arm detection.\n'
              '\n'
              'none: No field-level normalization. Use only when raw intensities are already '
              'comparable.\n'
              '\n'
              'outside_nuclei: Estimates background from voxels outside the nuclei.\n'
              '\n'
              'nuclear_low_percentile: Uses low-intensity voxels inside nuclei as background.\n'
              '\n'
              'whole_image_low_percentile: Uses low-intensity voxels from the whole image.\n'
              '\n'
              'mixed_outside_or_low_percentile: Uses outside-nuclei background when available and '
              'falls back to percentile-based background when needed.\n'
              '\n'
              'How it affects the result: Good normalization helps the plugin compare each nucleus '
              'with the overall field context. This helps prevent false P/Q masks in nuclei where '
              'only noise is present.\n'
              '\n'
              'Practical advice: Start with mixed_outside_or_low_percentile. Use none only for '
              'very controlled images with stable background.',
 'background_percentile': 'Background percentile\n'
                          '\n'
                          'What it is: Low-intensity percentile used to estimate background when a '
                          'percentile-based normalization mode is used.\n'
                          '\n'
                          'How it affects the result: A higher percentile includes more voxels in '
                          'the background estimate. If too high, dim true signal may be treated as '
                          'background. A lower percentile uses only darker voxels, which can '
                          'underestimate background in noisy images.\n'
                          '\n'
                          'Increase when: Background is underestimated and too much weak '
                          'background is detected as signal.\n'
                          '\n'
                          'Decrease when: Dim true P/Q signal is being absorbed into the '
                          'background estimate.\n'
                          '\n'
                          'Practical advice: Values around the lower third of the intensity '
                          'distribution are often a useful starting point, but inspect results '
                          'visually.',
 'max_context_voxels': 'Max voxels for field context\n'
                       '\n'
                       'What it is: Maximum number of voxels sampled from the field to estimate '
                       'background and normalization statistics.\n'
                       '\n'
                       'How it affects the result: Larger samples give more stable field '
                       'statistics but take longer. Smaller samples are faster but can be noisier, '
                       'especially in heterogeneous fields.\n'
                       '\n'
                       'Increase when: Background normalization appears unstable between scenes or '
                       'fields.\n'
                       '\n'
                       'Decrease when: Preview speed is more important and the field background is '
                       'uniform.',
 'enable_gate': 'Enable explicit presence/absence gate\n'
                '\n'
                'What it is: Allows the plugin to reject a nucleus as having no convincing P or Q '
                'arm signal.\n'
                '\n'
                'How it affects the result: This is the main protection against false positives. '
                'Without the gate, a GMM can still divide pure noise into dim and bright classes '
                'and produce a false mask.\n'
                '\n'
                'Enable when: Some nuclei may lack true signal or when the channel has '
                'speckle/background noise.\n'
                '\n'
                'Disable when: You are debugging why masks are empty or when every nucleus should '
                'contain signal and the gate is clearly too strict.\n'
                '\n'
                'Practical advice: Keep enabled for final analysis unless you have a specific '
                'reason not to.',
 'min_delta_bic': 'Minimum Delta BIC / LLR\n'
                  '\n'
                  'What it is: Minimum evidence that a multi-component intensity model is better '
                  'than a simple one-component background-like model.\n'
                  '\n'
                  'How it affects the result: Higher values require clearer separation between '
                  'background-like and signal-like intensity classes. Lower values accept weaker '
                  'separation.\n'
                  '\n'
                  'Increase when: Nuclei without real P/Q signal still get masks.\n'
                  '\n'
                  'Decrease when: Visible but dim P/Q signal is rejected.\n'
                  '\n'
                  'Practical advice: Tune this together with Minimum signal SNR and Minimum mean '
                  'posterior. It is a gate parameter, not a boundary parameter.',
 'min_snr': 'Minimum signal SNR\n'
            '\n'
            'What it is: Minimum signal-to-noise-like contrast required for the bright part of the '
            'nuclear intensity distribution.\n'
            '\n'
            'How it affects the result: Higher SNR thresholds make detection more conservative and '
            'reject noisy detections. Lower thresholds recover dim signal but may allow noise.\n'
            '\n'
            'Increase when: Background speckles are accepted.\n'
            '\n'
            'Decrease when: True visible arm signal is rejected by the gate.\n'
            '\n'
            'Practical advice: If masks are empty but signal is visible, lower this before '
            'changing boundary cleanup. If noise is accepted in nuclei with no signal, raise this.',
 'min_signal_fraction': 'Minimum expected signal fraction\n'
                        '\n'
                        'What it is: Minimum fraction of the nucleus expected to be signal-like '
                        'before accepting a P/Q detection.\n'
                        '\n'
                        'How it affects the result: Higher values reject tiny speckles. Lower '
                        'values allow very small territories.\n'
                        '\n'
                        'Increase when: Very small dots or isolated noise voxels are accepted as '
                        'P/Q arms.\n'
                        '\n'
                        'Decrease when: True P/Q territories are very small and are being '
                        'rejected.\n'
                        '\n'
                        'Practical advice: This is a presence-gate parameter. It should be set low '
                        'enough to allow small real objects but high enough to reject single-speck '
                        'detections.',
 'max_signal_fraction': 'Maximum expected signal fraction\n'
                        '\n'
                        'What it is: Maximum fraction of a nucleus that can be classified as '
                        'signal-like during the presence gate.\n'
                        '\n'
                        'How it affects the result: It prevents the plugin from labeling a very '
                        'large portion of a nucleus as P or Q signal when the entire nucleus has '
                        'elevated background.\n'
                        '\n'
                        'Decrease when: Masks are too broad or most of the nucleus is being called '
                        'P/Q arm.\n'
                        '\n'
                        'Increase when: True signal genuinely occupies a large fraction of the '
                        'nucleus and is being incorrectly rejected.\n'
                        '\n'
                        'Practical advice: If this threshold is too high, background gradients may '
                        'pass. If too low, large true territories can be rejected.',
 'min_mean_posterior': 'Minimum mean posterior\n'
                       '\n'
                       'What it is: Minimum average GMM signal probability among voxels considered '
                       'signal-like.\n'
                       '\n'
                       'How it affects the result: Higher values require more confident signal '
                       'probabilities. Lower values accept more ambiguous or dim signal.\n'
                       '\n'
                       'Increase when: Uncertain background is being accepted.\n'
                       '\n'
                       'Decrease when: Visible but weak signal is rejected.\n'
                       '\n'
                       'Practical advice: This parameter is useful when the GMM technically finds '
                       'a signal class but the probabilities are not convincing.',
 'prob_threshold': 'Probability threshold\n'
                   '\n'
                   'What it is: Converts the GMM probability map into a binary arm mask. A voxel '
                   'is included when its signal probability is greater than or equal to this '
                   'threshold.\n'
                   '\n'
                   'How it affects the result: Higher values shrink masks and keep only '
                   'high-confidence voxels. Lower values expand masks and include dimmer or more '
                   'uncertain voxels.\n'
                   '\n'
                   'Increase when: Masks include background, halos, or uncertain edges.\n'
                   '\n'
                   'Decrease when: True signal is visible but the mask misses dim parts.\n'
                   '\n'
                   'Practical advice: This is one of the most important boundary controls. Tune it '
                   'before using morphology or MRF/CRF.',
 'arm_smoothing': 'Arm Gaussian smoothing sigma\n'
                  '\n'
                  'What it is: Optional Gaussian smoothing applied to the P and Q channels before '
                  'arm detection.\n'
                  '\n'
                  'How it affects the result: Mild smoothing reduces speckle noise and makes '
                  'probabilities more stable. Excessive smoothing blurs object boundaries and can '
                  'merge real signal with adjacent background.\n'
                  '\n'
                  'Increase when: Raw P/Q channels contain isolated pixel or voxel noise.\n'
                  '\n'
                  'Decrease when: Boundaries become too blurry or small structures disappear.\n'
                  '\n'
                  'Practical advice: Start at 0.0. Use small values only if the raw channel is '
                  'visibly speckled.',
 'apply_morphology': 'Apply binary opening/closing after detection\n'
                     '\n'
                     'What it is: Enables traditional binary morphology after probability '
                     'thresholding and optional MRF/CRF refinement.\n'
                     '\n'
                     'How it affects the result: Opening removes small objects and thin '
                     'protrusions. Closing fills small holes and bridges small gaps. These '
                     'operations are not intensity-aware, so they can accidentally remove true '
                     'fragments or add adjacent background.\n'
                     '\n'
                     'Enable when: The mask has obvious small binary defects that cannot be fixed '
                     'by probability threshold or component selection.\n'
                     '\n'
                     'Disable when: Morphology attaches background to P/Q arms or erodes true arm '
                     'signal.\n'
                     '\n'
                     'Practical advice: Use sparingly. For boundary problems, MRF/CRF is often '
                     'safer because it uses intensity context.',
 'opening_radius': 'Binary opening radius\n'
                   '\n'
                   'What it is: Radius of the binary opening operation applied after detection '
                   'when morphology is enabled.\n'
                   '\n'
                   'How it affects the result: Larger opening removes more small islands and thin '
                   'protrusions. It can also erode real small arm fragments.\n'
                   '\n'
                   'Increase when: Small isolated specks remain after component filtering.\n'
                   '\n'
                   'Decrease when: Real signal is being eroded or fragmented.\n'
                   '\n'
                   'Practical advice: Use 0 or 1 for most cases. Larger values should be checked '
                   'carefully in 3D.',
 'closing_radius': 'Binary closing radius\n'
                   '\n'
                   'What it is: Radius of the binary closing operation applied after detection '
                   'when morphology is enabled.\n'
                   '\n'
                   'How it affects the result: Larger closing fills holes and connects nearby '
                   'pieces. It can also bridge a true signal to nearby background or noise.\n'
                   '\n'
                   'Increase when: True arm signal is artificially broken by tiny gaps.\n'
                   '\n'
                   'Decrease when: Background adjacent to the arm is being added.\n'
                   '\n'
                   'Practical advice: Use 0 or 1 only when needed. If background is being attached '
                   'to the mask, turn closing off.',
 'min_arm_volume': 'Minimum arm volume\n'
                   '\n'
                   'What it is: Minimum physical volume required for an accepted P or Q '
                   'component.\n'
                   '\n'
                   'How it affects the result: Components smaller than this volume are removed or '
                   'penalized during component selection. It helps reject tiny false positives.\n'
                   '\n'
                   'Increase when: Tiny dots or speckles are accepted as arms.\n'
                   '\n'
                   'Decrease when: True small territories are removed.\n'
                   '\n'
                   'Mathematical meaning: Volume equals voxel count multiplied by Z, Y, and X '
                   'voxel size. Because it is in cubic micrometers, correct image metadata are '
                   'important.',
 'component_selection': 'Component selection\n'
                        '\n'
                        'What it is: Decides which connected 3D objects are kept after probability '
                        'thresholding, optional MRF/CRF refinement, and optional morphology. The '
                        'default is all_passing_score.\n'
                        '\n'
                        'none: Keeps the binary mask without object-level filtering.\n'
                        '\n'
                        'largest: Keeps the largest component that passes minimum volume.\n'
                        '\n'
                        'all_after_size_filter: Keeps all components that pass minimum volume.\n'
                        '\n'
                        'best_score: Scores components and keeps only the highest-scoring '
                        'component if it passes the score threshold.\n'
                        '\n'
                        'all_passing_score: Scores components and keeps every component whose '
                        'score passes the threshold.\n'
                        '\n'
                        'How it affects the result: This is an object-level filter. It does not '
                        'refine boundaries; it decides which detected pieces are plausible P/Q arm '
                        'objects.\n'
                        '\n'
                        'Practical advice: The default all_passing_score is useful when true P/Q '
                        'territories can appear as multiple separated 3D compartments. Use '
                        'best_score if you want to force one main object per nucleus.',
 'component_score': 'Component score threshold\n'
                    '\n'
                    'What it is: Minimum object score required for a component to be kept in '
                    'score-based modes.\n'
                    '\n'
                    'How it affects the result: Higher thresholds reject weak components. Lower '
                    'thresholds keep more components.\n'
                    '\n'
                    'Increase when: Noise components survive component selection.\n'
                    '\n'
                    'Decrease when: Real components are removed even though the mask looks '
                    'visually correct.\n'
                    '\n'
                    'Practical advice: Tune after probability threshold and gate parameters. If '
                    'this is too strict, a good mask can become empty after component filtering.',
 'comp_prob_w': 'Component weight: probability\n'
                '\n'
                'What it is: Weight for the average GMM signal probability of a component.\n'
                '\n'
                'How it affects the result: Higher values favor components whose voxels have high '
                'signal probability. Lower values make the score less dependent on GMM '
                'confidence.\n'
                '\n'
                'Increase when: Low-confidence fragments are kept.\n'
                '\n'
                'Decrease when: Dim but real components are rejected because their probabilities '
                'are moderate.\n'
                '\n'
                'Practical advice: This weight is useful for rejecting uncertain components that '
                'are not strongly supported by the probability map.',
 'comp_contrast_w': 'Component weight: contrast\n'
                    '\n'
                    'What it is: Weight for local intensity contrast between a component and its '
                    'nearby surroundings.\n'
                    '\n'
                    'How it affects the result: Higher values favor objects that are brighter than '
                    'their local neighborhood. Lower values allow diffuse objects with weak '
                    'boundaries.\n'
                    '\n'
                    'Increase when: Background patches or broad gradients are accepted.\n'
                    '\n'
                    'Decrease when: True P/Q signal is diffuse and has weak local contrast.\n'
                    '\n'
                    'Practical advice: This is often the most useful weight when background near '
                    'the arm is being included.',
 'comp_volume_w': 'Component weight: volume\n'
                  '\n'
                  'What it is: Weight for component volume in the component score.\n'
                  '\n'
                  'How it affects the result: Higher values favor larger coherent territories over '
                  'small specks. Lower values allow smaller objects to compete based on '
                  'probability and contrast.\n'
                  '\n'
                  'Increase when: Tiny noise components are chosen.\n'
                  '\n'
                  'Decrease when: True P/Q territories are small and a larger false object is '
                  'being preferred.\n'
                  '\n'
                  'Practical advice: Do not set this so high that size dominates probability and '
                  'contrast.',
 'comp_boundary_w': 'Component boundary penalty\n'
                    '\n'
                    'What it is: Penalty for components with rough, jagged, highly boundary-like '
                    'shapes.\n'
                    '\n'
                    'How it affects the result: Higher penalties reject speckled or irregular '
                    'objects. Lower penalties keep irregular true signal.\n'
                    '\n'
                    'Increase when: Masks include noisy rims, jagged fragments, or adjacent '
                    'background.\n'
                    '\n'
                    'Decrease when: Real P/Q territories are irregular or near the nuclear '
                    'boundary and are being rejected.\n'
                    '\n'
                    'Practical advice: Tune this carefully. Real chromosome territories may not be '
                    'perfectly round, so excessive penalty can remove valid signal.',
 'mrf_iterations': 'MRF iterations\n'
                   '\n'
                   'What it is: Number of neighborhood-refinement passes used by the MRF/CRF '
                   'method.\n'
                   '\n'
                   'How it affects the result: More iterations create stronger spatial '
                   'consistency, smoother boundaries, and more gap filling. Too many iterations '
                   'can over-smooth, over-expand, or connect nearby objects.\n'
                   '\n'
                   'Increase when: Boundaries remain jagged or isolated voxels remain after a '
                   'small number of iterations.\n'
                   '\n'
                   'Decrease when: Masks grow into background, become too smooth, or lose fine '
                   'detail.\n'
                   '\n'
                   'Practical advice: Start with a small to moderate value. Tune lambda and edge '
                   'sigma together with iterations.',
 'mrf_lambda': 'MRF lambda\n'
               '\n'
               'What it is: Strength of neighborhood agreement during MRF/CRF refinement.\n'
               '\n'
               'How it affects the result: Higher lambda makes neighboring voxels more likely to '
               'share the same label. This can remove isolated specks and smooth boundaries, but '
               'it can also pull background into the mask.\n'
               '\n'
               'Increase when: Masks are ragged, fragmented, or contain isolated noisy voxels.\n'
               '\n'
               'Decrease when: Masks over-expand, become too smooth, or connect to adjacent '
               'background.\n'
               '\n'
               'Practical advice: This is the main smoothing-strength control for MRF/CRF.',
 'mrf_edge_sigma': 'MRF edge sigma\n'
                   '\n'
                   'What it is: Controls how strongly image intensity edges protect boundaries '
                   'during MRF/CRF refinement.\n'
                   '\n'
                   'How it affects the result: Smaller values make the method more sensitive to '
                   'intensity changes and reduce smoothing across edges. Larger values allow more '
                   'smoothing across weak edges.\n'
                   '\n'
                   'Decrease when: Masks leak into adjacent background or cross a visible '
                   'boundary.\n'
                   '\n'
                   'Increase when: True signal remains fragmented because weak internal edges '
                   'prevent filling.\n'
                   '\n'
                   'Practical advice: If MRF/CRF adds background next to P/Q arms, reduce edge '
                   'sigma before increasing component penalties.',
 'contact_radius': 'Contact dilation radius\n'
                   '\n'
                   'What it is: Voxel dilation radius used to decide whether P and Q masks are in '
                   'contact.\n'
                   '\n'
                   'How it affects the result: A radius of 0 counts strict overlap/touching only. '
                   'A positive radius dilates one mask before testing contact, allowing '
                   'near-touching territories to count as contact.\n'
                   '\n'
                   'Increase when: You want a more tolerant contact definition.\n'
                   '\n'
                   'Decrease when: You want only direct overlap or direct adjacency.\n'
                   '\n'
                   'Practical advice: Keep the value consistent across experiments because it '
                   'directly affects contact frequency.',
 'n_shells': 'Radial shells\n'
             '\n'
             'What it is: Number of concentric nuclear shells used for shell-style radial '
             'summaries.\n'
             '\n'
             'How it affects the result: More shells provide finer radial bins but can be noisier. '
             'Fewer shells are more stable but less detailed.\n'
             '\n'
             'Important note: The main radial output columns use a continuous 3D '
             'distance-transform radial coordinate from 0 near the nuclear center to 1 near the '
             'nuclear surface. Shell fractions are an additional binned summary.\n'
             '\n'
             'Practical advice: The default is usually sufficient unless you specifically need '
             'finer radial bins.',
 'preview_limit': 'Preview nucleus limit\n'
                  '\n'
                  'What it is: Maximum number of nuclei used for P/Q arm preview. The default is '
                  '0, which means all nuclei.\n'
                  '\n'
                  'How it affects the result: This affects only interactive preview speed and the '
                  'displayed preview masks. It does not limit final analysis unless Analysis '
                  'nucleus limit is also changed.\n'
                  '\n'
                  'Increase when: You want to preview a fixed number of nuclei rather than all '
                  'nuclei.\n'
                  '\n'
                  'Decrease when: You want faster preview or want to return to the all-nuclei '
                  'default by setting the value to 0.\n'
                  '\n'
                  'Practical advice: Use 0 when you want the preview to represent the full scene. '
                  'Temporarily use a smaller number only when tuning is slow.',
 'analysis_limit': 'Analysis nucleus limit\n'
                   '\n'
                   'What it is: Maximum number of nuclei analyzed during final output generation. '
                   'A value of 0 means all nuclei.\n'
                   '\n'
                   'How it affects the result: This directly determines how many nuclei appear in '
                   'the final CSV and output masks.\n'
                   '\n'
                   'Use a small value when: You are testing outputs or debugging settings.\n'
                   '\n'
                   'Use 0 when: You are running the final analysis.\n'
                   '\n'
                   'Practical advice: Always check this before final runs so you do not '
                   'accidentally analyze only a preview subset.',
 'auto_preview': 'Live-update P/Q preview when arm parameters change\n'
                 '\n'
                 'What it is: Automatically reruns P/Q arm preview after arm parameters change.\n'
                 '\n'
                 'How it affects the result: It does not change the algorithm; it only controls '
                 'whether preview updates automatically.\n'
                 '\n'
                 'Enable when: Images are small or preview is fast.\n'
                 '\n'
                 'Disable when: Previews are slow, you are changing multiple parameters, or you '
                 'want full control over when preview reruns.',
 'save_qc': 'Save QC max projections\n'
            '\n'
            'What it is: Saves maximum-projection QC TIFF images for raw channels and nuclei '
            'labels.\n'
            '\n'
            'How it affects the result: It does not affect segmentation or measurements. It '
            'provides quick visual files for checking output quality.\n'
            '\n'
            'Practical advice: Keep enabled for final runs. Disable only when disk space is '
            'limited and you do not need QC images.',
 'save_label_masks': 'Save arm label masks by nucleus\n'
                     '\n'
                     'What it is: Saves P, Q, and overlap label images in which each arm voxel '
                     'stores the ID of the parent nucleus.\n'
                     '\n'
                     'How it affects the result: It does not change measurements, but it makes it '
                     'easier to inspect which P/Q mask belongs to which nucleus.\n'
                     '\n'
                     'Practical advice: Keep enabled when you need traceability between CSV rows '
                     'and masks. Disable only to reduce output size.',
 'save_prob_maps': 'Save probability maps\n'
                   '\n'
                   'What it is: Saves voxel-wise P and Q probability maps as TIFF files.\n'
                   '\n'
                   'How it affects the result: It does not change the final masks. It saves the '
                   'intermediate confidence maps used before thresholding, MRF/CRF refinement, and '
                   'component selection.\n'
                   '\n'
                   'Practical advice: Keep enabled while developing and troubleshooting settings. '
                   'Disable for final high-throughput runs if disk space is a concern.',
 'reuse_nuclei': 'Analyze using current nuclei preview if available\n'
                 '\n'
                 'What it is: Reuses the nuclei labels currently shown in napari when running '
                 'final analysis, if nuclei parameters have not changed.\n'
                 '\n'
                 'How it affects the result: It saves time because Cellpose does not rerun. If '
                 'nuclei parameters changed after preview, the plugin reruns nuclei segmentation.\n'
                 '\n'
                 'Use when: You have inspected the nuclei preview and only changed P/Q arm '
                 'parameters.\n'
                 '\n'
                 'Do not use when: You want to force a fresh nuclei segmentation or suspect the '
                 'preview is outdated.'}
